"""
ollama_service.py — Local Ollama / LM Studio LLM Service
Enables offline AI operations (course difficulty assessment, natural language rule evaluation,
and executive timetable summaries) using local LLM endpoints.
Default Ollama URL: http://localhost:11434
Default LM Studio URL: http://localhost:1234/v1
"""
import json
import urllib.request
import urllib.error

DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_MODEL = "llama3.2"


def check_ollama_status(base_url: str = DEFAULT_OLLAMA_URL) -> dict:
    """Check if local Ollama server is running and reachable."""
    try:
        req = urllib.request.Request(f"{base_url.rstrip('/')}/api/tags", headers={"User-Agent": "ExamCellAgent/1.0"})
        with urllib.request.urlopen(req, timeout=3) as resp:
            if resp.status == 200:
                data = json.loads(resp.read().decode('utf-8'))
                models = [m.get("name") for m in data.get("models", [])]
                return {"status": "ONLINE", "models": models, "url": base_url}
    except Exception as e:
        return {"status": "OFFLINE", "error": str(e), "url": base_url}
    return {"status": "OFFLINE", "url": base_url}


def query_ollama(prompt: str, system_prompt: str = None, base_url: str = DEFAULT_OLLAMA_URL, model: str = DEFAULT_MODEL) -> str:
    """Send prompt request to local Ollama REST API endpoint."""
    target_url = f"{base_url.rstrip('/')}/api/generate"
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }
    if system_prompt:
        payload["system"] = system_prompt

    data_bytes = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(target_url, data=data_bytes, headers={"Content-Type": "application/json"})
    
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            if resp.status == 200:
                res_json = json.loads(resp.read().decode('utf-8'))
                return res_json.get("response", "").strip()
    except Exception as e:
        print(f"Local Ollama call failed ({base_url}): {e}")
        return ""
    return ""


def assess_course_difficulties_ollama(courses: list, base_url: str = DEFAULT_OLLAMA_URL, model: str = DEFAULT_MODEL) -> dict:
    """
    Use local Ollama model to assess difficulty for a list of course codes.
    Returns: {course_code: "hard" | "medium" | "easy"}
    """
    if not courses:
        return {}

    course_list_str = ", ".join([c if isinstance(c, str) else c.get("course_code", "") for c in courses])
    
    system_prompt = "You are an academic expert in engineering curriculum at Sri Eshwar College. You tag courses as 'hard', 'medium', or 'easy'."
    prompt = f"""Assess difficulty for these engineering courses: {course_list_str}
Respond strictly in JSON format mapping course code to difficulty level ("hard", "medium", "easy").
Example output: {{"U23MA204": "hard", "U23CS403": "medium"}}
JSON Output:"""

    response_text = query_ollama(prompt, system_prompt=system_prompt, base_url=base_url, model=model)
    
    # Parse JSON from response
    try:
        # Extract JSON substring if wrapped in markdown code blocks
        if "```" in response_text:
            response_text = response_text.split("```")[1]
            if response_text.startswith("json"):
                response_text = response_text[4:]
        diff_map = json.loads(response_text.strip())
        return {k.upper(): str(v).lower() for k, v in diff_map.items()}
    except Exception:
        # Heuristic fallback if local LLM response is not strict JSON
        heuristic_map = {}
        for c in courses:
            code = c if isinstance(c, str) else c.get("course_code", "")
            code_u = code.upper()
            if any(k in code_u for k in ["MA", "MATH", "DSP", "ALGO", "DSAA", "ELECTRO", "SIGNAL"]):
                heuristic_map[code_u] = "hard"
            elif any(k in code_u for k in ["HS", "ENG", "ENV", "VAL", "SOFT"]):
                heuristic_map[code_u] = "easy"
            else:
                heuristic_map[code_u] = "medium"
        return heuristic_map


def generate_schedule_summary_ollama(schedule_summary_data: dict, base_url: str = DEFAULT_OLLAMA_URL, model: str = DEFAULT_MODEL) -> str:
    """Generate executive summary using local Ollama model."""
    prompt = f"""Summarize this exam schedule generated by Exam Cell AI:
Start Date: {schedule_summary_data.get('start_date')}
End Date: {schedule_summary_data.get('end_date')}
Total Regular Exams: {len(schedule_summary_data.get('regular_exams', []))}
Total Arrear Exams: {len(schedule_summary_data.get('arrear_exams', []))}

Pattern: Day 1 FN (3rd Sem), Day 1 AN (5th Sem), Day 2 FN (7th Sem), Day 2 AN (Arrears).
Provide a brief, 3-paragraph professional executive summary for the Exam Controller.
"""
    summary = query_ollama(prompt, base_url=base_url, model=model)
    if not summary:
        summary = f"Schedule generated successfully for window {schedule_summary_data.get('start_date')} to {schedule_summary_data.get('end_date')}. Total regular exams scheduled: {len(schedule_summary_data.get('regular_exams', []))}, total arrear exams: {len(schedule_summary_data.get('arrear_exams', []))}."
    return summary
